name = "true-freeze-site-worker"
workers_dev = true
main = "./site-worker.js"
compatibility_date = "2022-05-06"

kv_namespaces = [
    { binding = "MERKLE", id = "ff53ffae406b4524bed6f687139434ea", preview_id = "bbef6879c00b4abd9759e3d22e745b3a" }
]

[site]
bucket = "./build"

[build]
    command = "yarn run build"

[vars]
REACT_APP_MORALIS_APPLICATION_ID = "CBpJYHbr7dwiMXGkqly8I4LFNtkZU0weADUP3UrF"
REACT_APP_MORALIS_SERVER_URL = "https://dcfjavlowgmp.usemoralis.com:2053/server"
GENERATE_SOURCEMAP=true