name = "true-freeze-site-worker"
workers_dev = true
main = "./site-worker.js"
compatibility_date = "2022-05-06"

kv_namespaces = [
    { binding = "MERKLE", id = "fe4dccc804044f4ea43f91c58db82e4b", preview_id = "2b91cd119e064fccb2633cd949ea7107" }
]

[site]
bucket = "./build"

[build]
    command = "yarn run build"

[vars]
REACT_APP_MORALIS_APPLICATION_ID = "CBpJYHbr7dwiMXGkqly8I4LFNtkZU0weADUP3UrF"
REACT_APP_MORALIS_SERVER_URL = "https://dcfjavlowgmp.usemoralis.com:2053/server"
GENERATE_SOURCEMAP=true